name: deploy
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          git clone git@github.com:gderaco/cryptocurrencyircbot.git ircbot
          cd ircbot
          cp ~/.local/share/cryptocurrencyircbot/config.json .
          docker build -t ircbot . && docker run ircbot
          rm -rf ircbot 
