name: deploy
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: git clone https://github.com/gderaco/cryptocurrencyircbot.git ircbot && cd ircbot && docker build -t ircbot . && docker run ircbot && rm -rf ircbot 
